<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Crisis Supports</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

	<div class="container">
		<center>
			<p style="font-size: 45px !important">Crisis Supports</p>
		</center>
		<br>
		<p><b>School Name: </b>{{ $schoolProfile->schoolName }}</p>
		<p><b>Generated By: </b>{{$userName}}</p>
		<p><b>Report Generated at: </b>{{$reportDate}}</p>
		<hr>
		@if(count($crisisSupport))
			@foreach($crisisSupport as $res)
			<div>
				<p><b>Name: </b>{{$res->name}}</p>
				<p><b>Phone Number: </b>{{$res->phoneNumber}}</p>
				<p><b>Website: </b>{{$res->website}}</p>
				<p><b>Service: </b>{{$res->serviceTypeId}}</p>
			</div>
			<hr>
			@endforeach
		@else
			<div>
				<center>
					No Data Found
				</center>
			</div>
		@endif
	</div>
	
</body>
</html>